import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <SidebarProvider>
      <body className="antialiased">
        {children}
        <SidebarTrigger />
      </body>
      </SidebarProvider>
    </html>
  );
};

export default RootLayout;
